#!/bin/bash

rm profile.cov

set -e
for dir in $(find . -maxdepth 10 -not -path './.git*' -not -path '*/_*' -type d);
do
if ls $dir/*.go &> /dev/null; then
    go test -v -coverprofile=$dir/profile.tmp $dir
    if [ -f $dir/profile.tmp ]
    then
        cat $dir/profile.tmp | tail -n +2 >> profile.cov
        rm $dir/profile.tmp
    fi
fi
done

echo "mode: set" | cat - profile.cov > /tmp/out && mv /tmp/out profile.cov
go tool cover -func profile.cov
go tool cover -html=profile.cov
